"""
Advanced PDF Report Generator
مولد التقارير المتطور
"""

import os
from datetime import datetime, timedelta
import json
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import io
import base64

class PDFReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
        
    def setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.darkblue
        )
        
        # Subtitle style
        self.subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=self.styles['Heading2'],
            fontSize=18,
            spaceAfter=20,
            alignment=TA_CENTER,
            textColor=colors.darkgreen
        )
        
        # Header style
        self.header_style = ParagraphStyle(
            'CustomHeader',
            parent=self.styles['Heading3'],
            fontSize=14,
            spaceAfter=15,
            textColor=colors.darkred
        )
        
        # Normal text style
        self.normal_style = ParagraphStyle(
            'CustomNormal',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            alignment=TA_LEFT
        )
        
        # Alert style
        self.alert_style = ParagraphStyle(
            'CustomAlert',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            alignment=TA_LEFT,
            textColor=colors.red
        )
        
        # Success style
        self.success_style = ParagraphStyle(
            'CustomSuccess',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            alignment=TA_LEFT,
            textColor=colors.green
        )
    
    def create_exam_report(self, data, output_path="exam_report.pdf"):
        """Create comprehensive exam monitoring report"""
        doc = SimpleDocTemplate(output_path, pagesize=A4)
        story = []
        
        # Title page
        story.extend(self.create_title_page(data))
        story.append(Spacer(1, 20))
        
        # Executive summary
        story.extend(self.create_executive_summary(data))
        story.append(Spacer(1, 20))
        
        # Detailed analysis
        story.extend(self.create_detailed_analysis(data))
        story.append(Spacer(1, 20))
        
        # Charts and graphs
        story.extend(self.create_charts_section(data))
        story.append(Spacer(1, 20))
        
        # Recommendations
        story.extend(self.create_recommendations(data))
        story.append(Spacer(1, 20))
        
        # Appendices
        story.extend(self.create_appendices(data))
        
        # Build PDF
        doc.build(story)
        print(f"✅ PDF report generated: {output_path}")
        return output_path
    
    def create_title_page(self, data):
        """Create title page"""
        elements = []
        
        # Main title
        title = Paragraph("AI Exam Monitoring Report", self.title_style)
        elements.append(title)
        elements.append(Spacer(1, 40))
        
        # Subtitle
        subtitle = Paragraph("Advanced Cheating Detection Analysis", self.subtitle_style)
        elements.append(subtitle)
        elements.append(Spacer(1, 60))
        
        # Report details
        details_data = [
            ['Report Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ['Monitoring Period:', data.get('period', 'N/A')],
            ['Total Students:', str(data.get('total_students', 0))],
            ['Total Alerts:', str(data.get('total_alerts', 0))],
            ['Average Risk Score:', f"{data.get('avg_risk_score', 0):.1f}/100"]
        ]
        
        details_table = Table(details_data, colWidths=[2*inch, 3*inch])
        details_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(details_table)
        elements.append(Spacer(1, 40))
        
        # Footer
        footer = Paragraph("Generated by Advanced AI Exam Monitoring System v2.0", self.normal_style)
        elements.append(footer)
        
        return elements
    
    def create_executive_summary(self, data):
        """Create executive summary section"""
        elements = []
        
        # Section header
        header = Paragraph("Executive Summary", self.header_style)
        elements.append(header)
        
        # Summary text
        total_students = data.get('total_students', 0)
        total_alerts = data.get('total_alerts', 0)
        avg_score = data.get('avg_risk_score', 0)
        
        summary_text = f"""
        This report presents a comprehensive analysis of the AI-powered exam monitoring session. 
        The system monitored {total_students} students and generated {total_alerts} alerts during the examination period.
        
        The average risk score across all students was {avg_score:.1f}/100, indicating the overall level of suspicious activity detected.
        The AI system successfully identified various types of cheating attempts including face movement violations, 
        suspicious audio patterns, and unauthorized object usage.
        """
        
        summary = Paragraph(summary_text, self.normal_style)
        elements.append(summary)
        
        # Key findings table
        key_findings = [
            ['Finding', 'Count', 'Percentage'],
            ['Face Movement Violations', str(data.get('face_movements', 0)), f"{data.get('face_movement_pct', 0):.1f}%"],
            ['Audio Violations', str(data.get('audio_violations', 0)), f"{data.get('audio_violation_pct', 0):.1f}%"],
            ['Object Violations', str(data.get('object_violations', 0)), f"{data.get('object_violation_pct', 0):.1f}%"],
            ['Multiple People', str(data.get('multiple_people', 0)), f"{data.get('multiple_people_pct', 0):.1f}%"]
        ]
        
        findings_table = Table(key_findings, colWidths=[2.5*inch, 1*inch, 1*inch])
        findings_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(Spacer(1, 20))
        elements.append(findings_table)
        
        return elements
    
    def create_detailed_analysis(self, data):
        """Create detailed analysis section"""
        elements = []
        
        # Section header
        header = Paragraph("Detailed Analysis", self.header_style)
        elements.append(header)
        
        # Face movement analysis
        face_header = Paragraph("Face Movement Analysis", self.subtitle_style)
        elements.append(face_header)
        
        face_text = f"""
        The system detected {data.get('face_movements', 0)} face movement violations during the exam.
        These violations occurred when students looked away from the screen for extended periods.
        
        Direction breakdown:
        • Right: {data.get('right_movements', 0)} violations
        • Left: {data.get('left_movements', 0)} violations  
        • Up: {data.get('up_movements', 0)} violations
        • Down: {data.get('down_movements', 0)} violations
        """
        
        face_analysis = Paragraph(face_text, self.normal_style)
        elements.append(face_analysis)
        elements.append(Spacer(1, 15))
        
        # Audio analysis
        audio_header = Paragraph("Audio Pattern Analysis", self.subtitle_style)
        elements.append(audio_header)
        
        audio_text = f"""
        Audio monitoring detected {data.get('audio_violations', 0)} suspicious audio patterns:
        
        • Whispering: {data.get('whispering_count', 0)} instances
        • Talking: {data.get('talking_count', 0)} instances
        • Keyboard Activity: {data.get('keyboard_count', 0)} instances
        • Paper Rustling: {data.get('paper_count', 0)} instances
        • Phone Vibrations: {data.get('phone_count', 0)} instances
        """
        
        audio_analysis = Paragraph(audio_text, self.normal_style)
        elements.append(audio_analysis)
        elements.append(Spacer(1, 15))
        
        # Object detection analysis
        object_header = Paragraph("Unauthorized Object Detection", self.subtitle_style)
        elements.append(object_header)
        
        object_text = f"""
        The AI system identified {data.get('object_violations', 0)} unauthorized objects:
        
        • Cell Phones: {data.get('phones_detected', 0)} instances
        • Books/Notes: {data.get('books_detected', 0)} instances
        • Laptops/Tablets: {data.get('laptops_detected', 0)} instances
        • Headphones: {data.get('headphones_detected', 0)} instances
        """
        
        object_analysis = Paragraph(object_text, self.normal_style)
        elements.append(object_analysis)
        
        return elements
    
    def create_charts_section(self, data):
        """Create charts and graphs section"""
        elements = []
        
        # Section header
        header = Paragraph("Visual Analytics", self.header_style)
        elements.append(header)
        
        # Create sample charts (in real implementation, these would be generated from actual data)
        charts_text = """
        This section contains visual representations of the monitoring data including:
        
        • Alert frequency over time
        • Violation type distribution
        • Student risk score distribution
        • Face movement patterns
        • Audio detection patterns
        
        Charts are generated using matplotlib and embedded directly in the PDF.
        """
        
        charts_desc = Paragraph(charts_text, self.normal_style)
        elements.append(charts_desc)
        elements.append(Spacer(1, 20))
        
        # Note about charts
        note = Paragraph("Note: Charts are generated based on the monitoring data and provide visual insights into cheating patterns.", self.normal_style)
        elements.append(note)
        
        return elements
    
    def create_recommendations(self, data):
        """Create recommendations section"""
        elements = []
        
        # Section header
        header = Paragraph("Recommendations", self.header_style)
        elements.append(header)
        
        recommendations_text = """
        Based on the analysis of this monitoring session, the following recommendations are provided:
        
        1. **Immediate Actions:**
           • Review high-risk students (score > 70) for potential disciplinary action
           • Investigate students with multiple violation types
           • Address technical issues that may have caused false positives
        
        2. **System Improvements:**
           • Adjust sensitivity thresholds based on false positive rates
           • Implement additional audio analysis for better accuracy
           • Consider adding behavioral pattern recognition
        
        3. **Policy Updates:**
           • Review exam room setup requirements
           • Update student guidelines for online exams
           • Establish clear consequences for different violation types
        
        4. **Training and Education:**
           • Provide student training on proper exam conduct
           • Train proctors on interpreting AI-generated alerts
           • Regular system accuracy reviews
        """
        
        recommendations = Paragraph(recommendations_text, self.normal_style)
        elements.append(recommendations)
        
        return elements
    
    def create_appendices(self, data):
        """Create appendices section"""
        elements = []
        
        # Section header
        header = Paragraph("Appendices", self.header_style)
        elements.append(header)
        
        # Appendix A: Technical Details
        tech_header = Paragraph("Appendix A: Technical Details", self.subtitle_style)
        elements.append(tech_header)
        
        tech_text = f"""
        **System Configuration:**
        • AI Model: YOLOv8 + MediaPipe Face Mesh
        • Face Movement Threshold: {data.get('face_threshold', 3)} seconds
        • Audio Sensitivity: {data.get('audio_sensitivity', 'Medium')}
        • Detection Confidence: {data.get('detection_confidence', 0.5)}
        
        **Performance Metrics:**
        • Average Processing Time: {data.get('avg_processing_time', 'N/A')} ms
        • Detection Accuracy: {data.get('detection_accuracy', 'N/A')}%
        • False Positive Rate: {data.get('false_positive_rate', 'N/A')}%
        """
        
        tech_details = Paragraph(tech_text, self.normal_style)
        elements.append(tech_details)
        elements.append(Spacer(1, 20))
        
        # Appendix B: Alert Log
        alert_header = Paragraph("Appendix B: Alert Log Sample", self.subtitle_style)
        elements.append(alert_header)
        
        alert_text = """
        The following is a sample of alerts generated during the monitoring session:
        
        [Alert logs would be included here in the actual implementation]
        """
        
        alert_log = Paragraph(alert_text, self.normal_style)
        elements.append(alert_log)
        
        return elements
    
    def create_student_report(self, student_data, output_path="student_report.pdf"):
        """Create individual student report"""
        doc = SimpleDocTemplate(output_path, pagesize=A4)
        story = []
        
        # Title
        title = Paragraph(f"Student Report: {student_data.get('name', 'Unknown')}", self.title_style)
        story.append(title)
        story.append(Spacer(1, 20))
        
        # Student details
        details_data = [
            ['Student ID:', student_data.get('id', 'N/A')],
            ['Name:', student_data.get('name', 'N/A')],
            ['Exam Date:', student_data.get('exam_date', 'N/A')],
            ['Final Risk Score:', f"{student_data.get('risk_score', 0):.1f}/100"],
            ['Status:', student_data.get('status', 'N/A')]
        ]
        
        details_table = Table(details_data, colWidths=[2*inch, 3*inch])
        details_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(details_table)
        story.append(Spacer(1, 20))
        
        # Violations summary
        violations_header = Paragraph("Violations Summary", self.header_style)
        story.append(violations_header)
        
        violations_data = [
            ['Violation Type', 'Count', 'Severity'],
            ['Face Movement', str(student_data.get('face_movements', 0)), student_data.get('face_severity', 'Low')],
            ['Audio Violations', str(student_data.get('audio_violations', 0)), student_data.get('audio_severity', 'Low')],
            ['Object Violations', str(student_data.get('object_violations', 0)), student_data.get('object_severity', 'Low')],
            ['Other Violations', str(student_data.get('other_violations', 0)), student_data.get('other_severity', 'Low')]
        ]
        
        violations_table = Table(violations_data, colWidths=[2*inch, 1*inch, 1*inch])
        violations_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(violations_table)
        
        # Build PDF
        doc.build(story)
        print(f"✅ Student report generated: {output_path}")
        return output_path

# Test function
if __name__ == "__main__":
    generator = PDFReportGenerator()
    
    # Sample data
    sample_data = {
        'period': '2024-12-01 09:00 - 12:00',
        'total_students': 25,
        'total_alerts': 15,
        'avg_risk_score': 35.2,
        'face_movements': 8,
        'face_movement_pct': 32.0,
        'audio_violations': 5,
        'audio_violation_pct': 20.0,
        'object_violations': 2,
        'object_violation_pct': 8.0,
        'multiple_people': 0,
        'multiple_people_pct': 0.0,
        'right_movements': 3,
        'left_movements': 2,
        'up_movements': 2,
        'down_movements': 1,
        'whispering_count': 2,
        'talking_count': 2,
        'keyboard_count': 1,
        'paper_count': 0,
        'phone_count': 0,
        'phones_detected': 1,
        'books_detected': 1,
        'laptops_detected': 0,
        'headphones_detected': 0,
        'face_threshold': 3,
        'audio_sensitivity': 'Medium',
        'detection_confidence': 0.5
    }
    
    # Generate report
    generator.create_exam_report(sample_data, "sample_exam_report.pdf")
    print("✅ Sample report generated successfully!")
